branches:
  only:
    - master

os:
  - linux

dist: bionic

language: node_js

node_js:
  - "12"

before_install:
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y libopenjp2-tools
  - sudo apt-get install --no-install-recommends -y rpm
  - sudo apt-get install --no-install-recommends -y bsdtar
  - sudo apt-get install gcc-multilib g++-multilib
  - npm i -g npm
  - npm i -g yarn
  - echo "-----BEGIN RSA PRIVATE KEY-----" > $HOME/.ssh/id_rsa
  - echo "${GH_KEY}" | tr " " "\n" >> $HOME/.ssh/id_rsa
  - echo "-----END RSA PRIVATE KEY-----" >> $HOME/.ssh/id_rsa
  - chmod 600 $HOME/.ssh/id_rsa

install:
  - git submodule update --init --recursive

script:
  - cd heptagon-core
  - yarn
  - yarn electron:generate-icons
  - yarn electron:build

cache:
  yarn: true