skip_commits:
  message: /(\[skip ci\]|\[skip appveyor\])/

branches:
  only:
    - master

environment:
  GH_TOKEN:
    secure: HHISy+sGq57hKlEtc0o7esy0gVWqL+0LZjmvVQa38W66OfqEs/LBhJhtI6MIC66y
  GH_KEY:
    secure: jpW7W1hn2h8NX2VU8db4wzd7uq4gJEXW3x4aE/heVT1ymgOdvoMYF/NosXjiVGtNBwceg+krbpyiwaOLTPjQF9L1pvFlAyfpgC+bSMDdUOUkAJXHkhFoUtuML34XvFlxxC5uurqb9+lkOzYB0GvoMdvBT7Y1CSNaTzIOoBQBHluP5EDK7v2vOmbz30REnVISeeXLOYj8XVLURVZ69cr0tF+SQjuXB73P8zq3wTh/hItSVdKbd6X7ps62v2GBF2OYqZHLijzs0y9KPQCobxzqAUyKLkjqStjp+qh8wFOouva0zxLjEV1XSjRgWLAGXIOvQACw3tASJ0cJJLdoF68XiYnns89CxCt+dwRrJfIz1X7BdlrHF7xx3Xqd7srR9xxx39pHr0hYKZf571VtvRgJ1D4bx5FSxQkMm2C9o2hsEyQ56WsXp2Fidicbjr6b55mtm2ci7cqBHgzwsMXzDeEFNArPWy3DLDKn13hB2GJUv8/vSJnYU6JCW/C9/RbfoDFZTYHVC6sw2O+/EMKEniqeGvOaVVB71PSQDnpICeAu5DV0gOKn/c9X4hsARezwqOgfNZO+va6dLZMgeiveovTWl3WkqqCft4saqG8SGZCsm+7cDpMM6Y0JV++5jjL5Kv5ViKgZhwSlSKtRR5v3m4PB/rwOl8Uwa0KtlMo/8OR+C2AEZMitoki8iYZWTBMij89iMlK68DXdPb6N7nj56FbxmULFHE0No2cR2EfU3X/4olnKaEHF+eMNzdq+JWjOC0ViJb0bhWHgtSnE6uihD0XqIT07T321H7jKctAxEkWmHL6aYCoCHdwpfO8rIROb1GC73P1fjZZW7/V9XtQ7fnYG2E0m1Krsw8VSuspD0+/UWC+oRp4GNal2rMncRSgcuX2Mi0fsmA8SLb0vmB+eYtzdrF8BBr6tTp/LslINkn+KQfgsrwV3P1LK9KlayHgIBpV2BwtOyChM7R5hzpI8ut+RXBmZmdaOD1M4q0DhSbrA6V9e2PzQbt1ZYAdghWRUSIoKidTAix536OGFHxx7s/t4lQ5FRFqa0N5jBVtv5dmaphThh7gGUZfm5TAnPU5p9sp6auAqVBaGUbmQMKK7PstpJ/qmlUF0KBHsZW2E2FfiAFxiowdZ9IkW5NB0dSEXt2hpQ+zUjfplyrjd3vF27YFfqy73nM9KtXDRFuwc4bQvi6+mePrS0cyy5vo1IvT4C1mTA6D9m1ryUff9Z5S20Tee1LLfN90zvQiudV0dI6NdlYh4RLZJb2+6ADFyMTGUGlrdauUtlmUkwFPIpG9mqLga8pq/ULGWDxFPIQtMOwGfpO321ZIq6N6y3BqOSPq1erLUaCSMsW8jEOs9hjvHlyfc+IuRdls6g5U1unzQrNY94/CK3J6qXwF6Kmu/9ouQChcycSdWWFV+WPl9zMM/5j465dQaxq8ORhmze9NRgyYTA9zC7uUgeJCp40SViZXUofoEWr3DKadi8uO59QTxXnOn3j/JBcDt1fXzozo4y6wn8UgOXOO1xZbWLSJrZLuShUZA4R1fQAHHiBHXDwhqnKO/rpjzG50Jsjxkuas7AEVUGnaHkTXbu27kt1+iaMHTN7yqXPX1q2FbpJvwKKWz9zwKho+vh/pr/4QzqLVW6Y6dDAzgFvM6LnXLwyAnbFKm7NPqeHnm3IsagJ6I0WEjz4dA30UQL7Q/n3s+mUiT9kz5PbG3pon5Zyq6Emzx6HOwasq8xClPQ0QoVGYjTJNZn4T5KsaC370lMOVdNFZU3HWGpRlSh/F3qbJLCtl5TAr81i9ZGcxQWB0QedYv/weC/spPe8rIkliWtmTtAulBohtOjmmDWrZKQ4gEdVprLfochJe2gO8RysSO95c0unjufCwL0NNFDvz0IGGRkQrtIIOXEY/xzK4C41lb2YcDPUkoOoPzIXo7dpFndqpo7ZDkFI9HTo2z7tAv2wOf1M2xYHVDLKtoI+M6W1dppyQ/4Loy2dq5wc7MXIzcyAf/6TrD/NFh6XfZ5NnpiOcmtcjIxpRkbae358AiYGzob0nFQqvuRpWzENOMVWgCnrn4e0bc77SNIDOld8RLGixmEoa241GFBzWsNFTqjz2y+akMv9DSO6/mgWw5TWzqiFlvNW9OKgfMyKcHgiTNf5koXg/ypC5LHqNFTuycBfvNDp2SeaZwUNnSxvUyNhEJYKl+oyGOePMlO0nl+qQdoLk+hMCt8ndmdJEXMYqa9p4/Pse2PI8NCds8xtSScIS+sW3m4Ssm264YT2jF91H7eQ9+yfXx3FAij/dK3RKLWdXjppqXTCAYkmAFvZSaHF3zEbbtjY6mjulEbKrty+FyubhhEX9dKUkEWWgeZX6ODpqxSISCv2TglmYyog9UDIYX8VLAXS0n0TWklZJVyHQSLAqj3cKOG9yI6QRIBjszf7kGtNFvnZ/DBrGnoXqBmMWuZ6JDJDiEdmQ3at3wsyTEKiTq816wtJWmfjyyNEYwt5SbKDxPkkYi5SHdWlm/hr2ANAu6eOd/yI7gVYVBldqibLw6jKJdr92bFTYRs/JkmQ6aZDaKaga+34u+EI0BhL5UB2w4a4AeFXXXJk6meVCpTg/54OZH0zAXYZOo+7uLRR7Q6gv2f5mZhsVUEb4W5P2QtT0VkhUuJvWW5GgCh3gx2MmsNcFyiqivOrAe+H5DEASLM+XLGNbHXf7y8E0mMknO+kakIikGo4167ser+J2s7sPLbid9P4z7/QNCu/Yzui1Z3Qogz7V7mFnd3T/SRbQTI96uDdw5jLmgbJEEf7frjIH2ljExOAzinqbjNn8UuX9Ggr+d/Lt/vo0n/xsUpB1M5NWuog2xlboL7O+wFbLNfmZL1zcW0HE6uq85wskjSvvBSpzP/5CX8ijmqjt0RnTeKuBSj2FNQnsi9SJyPHBj7ySyHhvsbruMM1ejYzRZIxGKjmy+RECi/IGaXcimIf/DMD+97LMGmSETJQ2ZnJ6tguxXlCAHlg80zvPWm3kAqncYZqBer1xavtri7jgXMOkl2BOir1pBGahLYtGl8TFoRwrOfUlGGtQ4uXZF3oo1VJPVpYzYwiTklj2psnlGZD92v1MEeqx7lZrvmsRQX4jvLmdpvsraLaGT4QqIhKuHXpR9KkVQG3GX3Tl8Sg05DwuS/eFeXDbke/EnkOsSputrStGYsE1T1gnwEBBGYW7vVgZJ1Axz/pRZg+A2nD6oTBAp2Lgythh/Ripk9nazmIpNrPMPI6rimIdzyF8pgQYW8G0/4bzcOvEb+lHQjQpB4sDe1TLxQgiso96z+haRRTJHEdZoMIZwop7/4b4ai5EImPKB2qJe+nvZPZ2E6LMwpF5sx5BqcyQ15yuUr2m4aVClqrjhV2rVUp/oWDjPRcayLsbrtRl5SDwuHDwU

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

init:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:GH_KEY.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent
  - git config --global core.autocrlf input
  - git submodule update --init --recursive

install:
  - ps: Install-Product node 12 x64
  - npm i -g npm
  - npm i -g yarn
  - yarn

build_script:
  - yarn electron:generate-icons
  - yarn electron:build

test: off