skip_commits:
  message: /(\[skip ci\]|\[skip appveyor\])/

branches:
  only:
    - master

environment:
  GH_TOKEN:
    secure: HHISy+sGq57hKlEtc0o7esy0gVWqL+0LZjmvVQa38W66OfqEs/LBhJhtI6MIC66y
  GH_KEY:
    secure: I3EJ0/kaO+LvJSeCVMX2vvZzmWUZep7iNm8EwBulV8AQfMuzDZ5SNFdVeuGdEjFpy4J31q1fvNtWfrzfn8WmuJtCIDISB52pjF7prRVsdwLppCJyf4YzKVEH4Lu684CgG4pUXURCgOmrbDuS7CFNSpOGZoyIdwyDZpqkTRLD4iC1v4UN3XnPKWCbL8bz8vfzoeop0oVyY/y94M0AcKeD675PyuoZLckAQ5JxVLuLAkSrF6FSWD9vg2WM2XJx8trt7bZrSCzk1GTthb+pYXeHbyhiEyFTtY/huFR5QcpYqJyLBVexwJUxwHQiQF2+of1dr2zuvanVsfHNwv2Fboxf3ZVQDG7S+X5Yj6189SQyf+P8o8EWcUs2WU7t4xnl/NbR8k5rwnGzdyrwT29CTXWvNufMpGDfZUA7/EAYtf81DTJGuuhW5S/DewJ94vMPjbt/wNe2I+QvqByfyHtbB/uAuh/GHogxwbY62glOV6kRxd/A8nMKl6AqOYc20r6PM0yvi5j//QJDJfdhLNZ2ccYdA2Qv5iLwMKP3k2ztuxOYWSaSqEClRfesTYiOlquD/wLXBW/oTxdoFbvkbYmsyqolTCLbqSrQCmr+jZuHDQg+rqx5jsC9sij8IQh1qj1rfeoWfQ9fQqzje6LCass3xe2kX6Ugb76XNtb21AscrXp0qyyg361FccZurrd/E1es3Lt4TTQnEbljel21U+xkfiBFhScW3z1PZE4jKEEjgmW5MdqMERo3VNE6fY3bDd9ICkBYsf5CdmcqJ6Cg/IBABZJ17mzRZ8nuCeDdkmeM2JPABAZfI92FTH2wfpakMaXjUqc/ur7xiywmJBtE1R7zGbyXoLGu1WOCfSmO3peSEJV+hThpLIAh4s/IHjJglSL40tGxyD6nt0Xgcu//eM6oDYe+NFq6/EVUizv6pXKAtuQNTWFoBD+1MUWeBVkjfw4SaeCy2qxtrGxqYNEBdlWJc9QdhrkrKMF08lAjYzqeS5EF42IXoo5SH+EMO8mSq5tbJ3JS8p4NE1cOl97Okti+KUKFxpZlW2pVA0cXjoVOTB3UvLbWPtVbWenqOKcCPQ0kMfFhPza7+uqaI21X+swQltIdcW6QAddwneETdX72vnlCe1DA1Z5eOQVkjwLBD0vDL1wBzD6tgaExooqgnYC6fWI8KijTsUkDaabAdkcR6Aw61BmezRUil3f7a4bW23HO1Wf+S+C3nV4IxzwOU6fbp80opczEl46opi9PAHlzd2XQ4UGL4UKDJ+OWFs6vAtYYGj0k8JaoliMSecE6c9GvlEcZJw7P0LPEqPdWbgSt0+I0d2L6SW1m4GPOFlRirpfjZ85QcNkPEQkWOqcan3Uk7mIvSX5JNUsnLhRF0VtzGvijXgWYfWFvAUvr9mEf+ocVLImwUNwsi+B81uzaH4dlmd6WhFbjcmFUHKMqAVyVKnXfVcJlpuXVWWlZyroGCxs3jP/5u0JXFaYpRb0CbpHxy4F9MstZjt9092pJ3Ia9C9UCBhMf/oPVcK+w04VWuHcpJKZv57Y4l/dmuREU5V+pjVFbGHlwKsCTRjc+cDP5GnSNFOK3H8hg+yx4JLGj4/dAFAr6QHiIa7bBOgSGcEC1QemMxwAbCdUsURsO2hAOLFK5MxX2Ia/5BSQXRxKHsYyiquS1YOvJVcJNIhqiamlnTc77yECytN8gxEHtK767Zx+rpgh8DrptCinBTqpo3Z8N7UaRrz8nuYS55+9auBUo6x0rGkMJFHBvBjWoVMF5tERZuKphhFvlPwcy3gNELMVUlwsMQiSIRjqeZ3m7o8ORJ06bmy+osOe0qrpDFiNlWJL/KJSaG3xxmv5PTQ+qE1/TE0CszEsyYlHv2P727LYJg6A/sL/Dh26fxbKwdXnqNNHpahi3GVDGxJH7GE9bEkI8TvMkp+S/Bn+ymEzEg4QGw+Bbg0UTPMFQ0FvFEY1kYYvCvVs6tBclydT4XqwlpsL0JEwqIJQLdPQ8trLXUhJTljLj5epc/sbZXgRrr1+UeArTEMT25Y8T4Ml0xdctlB9cOw22Cw/mKG2xaQaowWmYM7GjhWde3uh8W6XKyIMm+ihIN49SqBaFbTH/VsOcC+1ODf88jDJ/RHuqdwCdMwAiDdmPZuf4rlzY1bY2ofIIsM1XZbk=

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

init:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:GH_KEY.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent

install:
  - ps: Install-Product node 12 x64
  - git config --global core.autocrlf input
  - git submodule update --init --recursive
  - npm i -g npm
  - npm i -g yarn
  - yarn

build_script:
  - yarn electron:generate-icons
  - yarn electron:build

test: off